export const BOOKING_OPERATIONAL_TIMEZONE =
  "Asia/Tehran";

export const BOOKING_IRAN_UTC_OFFSET_MINUTES =
  210;

export const BOOKING_SLOT_MINUTES =
  15;

export const BOOKING_SESSION_MINUTES =
  15;

export const BOOKING_MIN_LEAD_MINUTES =
  30;

export const BOOKING_MAX_HORIZON_DAYS =
  30;

export const BOOKING_MAX_AVAILABILITY_QUERY_DAYS =
  31;

export const BOOKING_STUDENT_CANCELLATION_CUTOFF_MINUTES =
  120;

export const BOOKING_MAX_UPCOMING_SESSIONS_PER_STUDENT =
  10;

export const BOOKING_MAX_WEEKLY_AVAILABILITY_RULES =
  28;

export const BOOKING_MAX_EXCEPTION_NOTE_LENGTH =
  500;

export const BOOKING_MAX_CANCELLATION_REASON_LENGTH =
  1000;
